securitytxt.settings:
  type: config_object
  label: 'Security.txt settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable security.txt'
    enabled_signature:
      type: boolean
      label: 'Enable Signature'
    contact_email:
      type: email
      label: 'Contact email'
    contact_phone:
      type: string
      label: 'Contact phone'
    contact_page_url:
      type: string
      label: 'Contact page URL'
    encryption_key_url:
      type: string
      label: 'Public key URL'
    expiry_date:
      type: integer
      label: 'Expiry date'
    policy_url:
      type: string
      label: 'Security policy URL'
    acknowledgement_url:
      type: string
      label: 'Acknowledgment page URL'
    signature_text:
      type: string
      label: 'Plain text PGP signature of security.txt'
